
services:
  backend:
    container_name: back-api
    build: 
      context: '.'
      dockerfile: ./container/backend/Dockerfile
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - 8000:8000
    tty: true
    depends_on:
      - db
  
  frontend:
    container_name: front
    build: 
      context: '.'
      dockerfile: ./container/frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/frontend
      - node_modules:/usr/src/frontend/node_modules # node_modules
    tty: true
    depends_on:
      - backend
  db:
    container_name: database
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
volumes:
  db:
  node_modules:
